<?php
echo "Question 1:";
echo "<br>";
echo " The string is: ".$strVar="Hello World!";
echo"<br>";
echo "the length of string is: ". strlen($strVar);
echo "<br>";
echo "<br>";
echo "Question 2:";
echo "<br>";
echo " The string is: ".$strVar="Hello World!";
echo"<br>";
echo "the reversed string is: ". strrev($strVar);
echo "<br>";
echo "<br>";
echo "Question 3:";
echo "<br>";
echo " The string is: ".$v1="Hello World!";
echo"<br>";
echo " The replace string is: ".$v2="Dolly";
echo"<br>";
echo "the replaced string is: ". str_replace("World",$v2,$v1);
echo "<br>";
echo "<br>";
echo "Question 4:";
echo "<br>";
echo " The string is:".$v1="This is ISI Class, learn programming here.";
echo "<br>";
echo "the number of words in the string is: ". str_word_count($v1);
echo "<br>";
echo "<br>";
echo "Question 5:";
echo "<br>";
echo " The string is:".$v1="This is ISI Class, learn programming here.";
echo "<br>";
echo "the number of words in the string is: ". strtoupper($v1);
echo "<br>";
echo "<br>";
echo "Question 6:";
echo "<br>";
echo " The string is:".$v1="This is ISI Class, learn programming here.";
echo "<br>";
echo "the number of words in the string is: ". strtoupper($v1);
echo "<br>";