<?php
echo "Question 1:";
echo"<br>";
$x=5*10;
echo "the answer 5*10 is: ".$x;
echo "<br>";
echo "<br>";
echo "Question 2:";
echo "<br>";
$x=10/2;
echo "the answer 10/2 is: ".$x;
echo "<br>";
echo "<br>";
echo "Question 3:";
echo "<br>";
$a=10;
$b=10;
$c=($a==$b)?"same":"not same";
echo"<br>";
echo "the asnwer to comparison is: ".$c ;
echo "<br>";
echo "<br>";
echo "Question 4:";
echo "<br>";
$a=10;
$b=10;
$c=($a!=$b)?" not same":"same";
echo"<br>";
echo "the asnwer to comparison is: ".$c ;
echo "<br>";
echo "<br>";
echo "Question 5:";
echo "<br>";
echo "Addition Operation Result: " .(40+22)."<br>";
echo "Substraction Operation Result: " .(62-40)."<br>";
echo "Multiplicatoin Operation Result: " .(84*10)."<br>";
echo "Division Operation Result: " .(21/10)."<br>";
echo "Modulus Operation Result: " .(12%10)."<br>";
$x=41;
$y=44;
echo "Increment Operation Result: " .(++$x)."<br>";
echo "Decrement Operation Result: " .(--$y)."<br>";
echo "<br>";
echo "Question 6:";
$a=10;
$b=5;
echo "<br>";
echo "Test1: a is ";
echo ($a==$b)?"equal":"not equal";
echo " to b";
echo "<br>";
echo "Test2: a is ";
echo ($a>$b)?"grater":"not grater";
echo " than b";
echo "<br>";
echo "Test3: a is ";
echo ($a<$b)?"less":"not less";
echo " than b";
echo "<br>";
echo "Test4: a is ";
echo ($a!=$b)?"not equal":"equal";
echo " than b";
echo "<br>";
echo "Test5: a is ";
echo ($a>=$b)?"either grater than or equal":"neither grater than or equal";
echo " to b";
echo "<br>";
echo "Test6: a is ";
echo ($a<=$b)?"neither grater than or equal":"either grater than or equal";
echo " to b";
echo "<br>";
echo "<br>";
echo "Question 7:";
$a=true;
$b=false;
echo "<br>";
echo "Test1: either a or b is";
echo ($a and $b)?" true":" false";
echo "<br>";
echo "Test2: either a or b is";
echo ($b and $a)?" true":" false";
echo "<br>";
echo "Test3: either a or b is";
echo ($a or $b)?" true":" false";
echo "<br>";
echo "Test4: either a or b is";
echo ($b or $a)?" true":" false";
echo "<br>";
echo "Test5: a is";
echo ($a==true)?" true":" false";
echo "<br>";
$b=true;
echo "Test6:  b is";
echo ($b==true)?" true":" false";
echo "<br>";
$a=false;
$b=false;
echo "Test7: a is";
echo ($a==true)?" true":" false";
echo "<br>";
echo "Test8:  b is";
echo ($b==true)?" true":" false";
echo "<br>";
echo "<br>";
echo "Question 8:";
$result=0;
echo "<br>";
echo "Addition operation Result :".(40+22);
echo "<br>";
$result=100+4;
echo "Addition and Assignment operation Result :".$result;
echo "<br>";
$result=100-38;
echo "Subtraction and Assignment operation Result :".$result;
echo "<br>";
$result=217*12;
echo "multiply and Assignment operation Result :".$result;
echo "<br>";
$result=496/8;
echo "Division and Assignment operation Result :".$result;
echo "<br>";
$result=60%40;
echo "modulus and Assignment operation Result :".$result;
echo "<br>";
echo "<br>";
echo "Question 9:";
$result=0;
$result=10+11;
echo "<br>";
echo "Test1: Value of result is";
echo ($result>20)?" 20":" 10";
echo "<br>";
echo "Test2: Value of result is";
$result=10+9;
echo ($result>20)?" 20":" 10";
echo "<br>";
echo "<br>";
